services:
  - type: web
    name: teacher-portal
    runtime: static
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: false
    envVars:
      - key: VITE_FIREBASE_API_KEY
        sync: false
      - key: VITE_FIREBASE_AUTH_DOMAIN
        sync: false
      - key: VITE_FIREBASE_PROJECT_ID
        sync: false
      - key: VITE_FIREBASE_STORAGE_BUCKET
        sync: false
      - key: VITE_FIREBASE_MESSAGING_SENDER_ID
        sync: false
      - key: VITE_FIREBASE_APP_ID
        sync: false
      - key: VITE_GEMINI_API_KEY
        sync: false
      - key: VITE_MAILER_URL
        sync: false
      - key: VITE_MAILER_SECRET
        sync: false
      - key: VITE_UPI_ID
        sync: false
